import Head from "next/head";
import Typography from "@mui/material/Typography";
import styles from '@/styles/Home.module.css'


export default function Page404() {

  return (
    <>
      <Head>
        <title>Anon Messaging</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typography variant="h4">
         404 | Page Not Found
        </Typography>
      </main>
    </>
  )
}
